[[VIC5]]
arch = "aarch64"
git-tree-sha1 = "2f23f120cf5863bf67f7771efed9d9f17333d4e7"
os = "macos"

    [[VIC5.download]]
    sha256 = "1e73fc64e263e50ed82b94e3e85c8788a44fb55999b28b27b006369849de2831"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.aarch64-apple-darwin.tar.gz"
[[VIC5]]
arch = "aarch64"
git-tree-sha1 = "91ba7e2316dfb42223ddb40f5ced2d20a84c1220"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "cd5938282ac54a427e991e3fc9f5fb4238504b73b8af2e609cf4664fa7c074a8"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.aarch64-linux-gnu.tar.gz"
[[VIC5]]
arch = "aarch64"
git-tree-sha1 = "fcca185be673f2537bc9f1f13d5d7f1fc0cd7823"
libc = "musl"
os = "linux"

    [[VIC5.download]]
    sha256 = "2265ea7c4840cb851cbe03be5f00e9de98c040530a8979ce496357d4e065da69"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.aarch64-linux-musl.tar.gz"
[[VIC5]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b060869462f42b840e1d208b691bc6abb8f6099"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "8ee0b87c3cd36c303b8f0439656be7ec979f9678339c167c32c9d41e096d120d"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.armv6l-linux-gnueabihf.tar.gz"
[[VIC5]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4e66a4a5bc9460b3e1c42e6f77c2c472931b89f"
libc = "musl"
os = "linux"

    [[VIC5.download]]
    sha256 = "03e20f9ec9489e86b8e52f474599d37d7be44832a1037a2303ae71a968cd0996"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.armv6l-linux-musleabihf.tar.gz"
[[VIC5]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af9a9550432e5fb923d8d7a966c834b44c31cc15"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "56cbac5360b36449b182707e15a0a749687998bf9a1d0b4c94877be03f27b524"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.armv7l-linux-gnueabihf.tar.gz"
[[VIC5]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d57ff43fce1c045ca9f4a0dbb6ee7e7b6b7f62c3"
libc = "musl"
os = "linux"

    [[VIC5.download]]
    sha256 = "c5073cc0cf04f008f6d5b862e122f1f785c93cd21ae93426ff971fd6c30d04ee"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.armv7l-linux-musleabihf.tar.gz"
[[VIC5]]
arch = "i686"
git-tree-sha1 = "6c5fa3f119785cf5167f7c2e0cd77da9e9cb30db"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "49ad390c422102ea4722c2aa0e58bef37f4fe5fdb79fa3ec3eef826c070905d7"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.i686-linux-gnu.tar.gz"
[[VIC5]]
arch = "i686"
git-tree-sha1 = "9139e3669e2fda8769a0b6c45eb70aed029f5e0c"
libc = "musl"
os = "linux"

    [[VIC5.download]]
    sha256 = "ebfa4c325451923c5a42d896f86d244418d6fdd86c7b58a933412223deb10822"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.i686-linux-musl.tar.gz"
[[VIC5]]
arch = "i686"
git-tree-sha1 = "e4877e2f6d40967a89b69e6cb345eac9341d1620"
os = "windows"

    [[VIC5.download]]
    sha256 = "f733a9d0b97e098979c06681b161f72b917b9f0ae286a84f582e4454e6e698da"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.i686-w64-mingw32.tar.gz"
[[VIC5]]
arch = "powerpc64le"
git-tree-sha1 = "e6265fb819ae4f073474c89d29b18ff1ea6c24ca"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "e07c6abfbe9b6b95e0e62c22ca15fce54fd74ce60afb163fa41b5a3c024c2152"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.powerpc64le-linux-gnu.tar.gz"
[[VIC5]]
arch = "x86_64"
git-tree-sha1 = "9b02c45dae42b73fdb8eca8873dfc9e669917e46"
os = "macos"

    [[VIC5.download]]
    sha256 = "eec648e85d7afb97c7ac07ced491e2a13655c9d041efe6281fd88ebf3736ed8c"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.x86_64-apple-darwin.tar.gz"
[[VIC5]]
arch = "x86_64"
git-tree-sha1 = "3047c5626f018277d8dcd9c730b7f516b4490ecd"
libc = "glibc"
os = "linux"

    [[VIC5.download]]
    sha256 = "86a4458fc152c1fafa88412ebdbf246e18df8dc4eb6a29487e00eeee9a3c9ebf"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.x86_64-linux-gnu.tar.gz"
[[VIC5]]
arch = "x86_64"
git-tree-sha1 = "3f09495c5305fd14e3a796dabc742186fc42f1c1"
libc = "musl"
os = "linux"

    [[VIC5.download]]
    sha256 = "e47cc848601554a7ed7e5aa9a3eac1735a342ae18b9bc8d0f8d35d4363218c20"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.x86_64-linux-musl.tar.gz"
[[VIC5]]
arch = "x86_64"
git-tree-sha1 = "1d118f50fb0fcb067fa2686ea33b742481eac342"
os = "freebsd"

    [[VIC5.download]]
    sha256 = "1f5038358a4738c568e0cc9611149485153fe61d089a5f48a85f6b9f109f059d"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[VIC5]]
arch = "x86_64"
git-tree-sha1 = "5d24f4f6dc7a400a364e36e1ff2bf856d73455d3"
os = "windows"

    [[VIC5.download]]
    sha256 = "47ca82f5f591531f42b9e4023388c88a2d08a2db17038d26ad97b984bbb574a5"
    url = "https://github.com/JuliaBinaryWrappers/VIC5_jll.jl/releases/download/VIC5-v0.1.2+0/VIC5.v0.1.2.x86_64-w64-mingw32.tar.gz"
